Repository ublue-os/aurora-lts, pull requests merged in 2025-03, with the labels that each got.

#6 fix: Fix build
  Justfile
  build_scripts/10-repos.sh
  build_scripts/20-core.sh
  build_scripts/30-desktop.sh
  build_scripts/40-utils.sh
  build_scripts/50-branding.sh
  build_scripts/60-prune.sh
  build_scripts/build.sh
  build_scripts/cleanup.sh
  build_scripts_overrides/dx/25-packages.sh
  build_scripts_overrides/dx/45-services.sh
  build_scripts_overrides/dx/45-uv.sh
  build_scripts_overrides/gdx/25-nvidia.sh
  build_scripts_overrides/gdx/35-pixi.sh
  build_scripts_overrides/hwe/45-nvtop.sh
  build_scripts_overrides/x86_64/41-ublue-brew.sh
  build_scripts_overrides/x86_64/hwe/25-hyperscale-kernel.sh
  system_files/usr/share/containers/storage.conf
  system_files_overrides/aarch64-dx/.gitkeep
  system_files_overrides/aarch64-hwe/.gitkeep
  system_files_overrides/aarch64/.gitkeep
  system_files_overrides/dx/.gitkeep
  system_files_overrides/hwe/.gitkeep
  system_files_overrides/x86_64-dx/.gitkeep
  system_files_overrides/x86_64-gdx/.gitkeep
  system_files_overrides/x86_64-hwe/.gitkeep
  system_files_overrides/x86_64/.gitkeep
Labels: size:L

#10 feat: add workflow and files to support live-iso build
  .github/workflows/build-iso.yml
  iso_files/configure_iso.sh
  system_files/etc/ublue-os/system-flatpaks.list
Labels: enhancement, size:L

#11 fix: add livesys to build iso action
  .github/workflows/build-iso.yml
Labels: size:XS

#12 fix: Correct os-release id
  build_scripts/50-branding.sh
Labels: size:XS, lgtm

#16 style: Enable quiet karg
  system_files/usr/lib/bootc/kargs.d/quiet.toml
Labels: enhancement, size:XS, lgtm
